files:
  - source: app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/strings.xml
    languages_mapping:
      android_code:
        de-rDE: de
        es-rES: es
        fr-rFR: fr
        it-rIT: it
        sr-rCS: sr
