files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
    languages_mapping: # https://developer.crowdin.com/language-codes/
      android_code:
        de: de
        es-ES: es
        fr: fr
        it: it
        sr-CS: values-b+sr+Latn
