package com.jocmp.basil

import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.util.UUID
import kotlin.test.assertEquals

class OPMLFileTest {
    @JvmField
    @Rule
    val folder = TemporaryFolder()

    @Test
    fun opmlDocument_serializes() {
        val accountPath = folder.newFile().toURI()
        val account = Account(
            id = "777",
            path = accountPath.resolve("test.opml"),
            database = InMemoryDatabaseProvider().forAccount("777")
        )

        account.folders.addAll(
            listOf(
                Folder(title = "Empty Folder"),
                Folder(
                    title = "Tech",
                    feeds = mutableListOf(
                        Feed(id = UUID.randomUUID().toString(), name = "The Verge", feedURL = "https://www.theverge.com/rss/index.xml"),
                        Feed(id = UUID.randomUUID().toString(), name = "Ars Technica", feedURL = "https://feeds.arstechnica.com/arstechnica/index")
                    )
                ),
                Folder(
                    title = "Programming",
                    feeds = mutableListOf(
                        Feed(id = UUID.randomUUID().toString(), name = "De Programmatica Ipsum", feedURL = "https://deprogrammaticaipsum.com/feed"),
                        Feed(id = UUID.randomUUID().toString(), name = "Ruby Weekly", feedURL = "https://cprss.s3.amazonaws.com/rubyweekly.com.xml"),
                    )
                )
            )
        )

        account.feeds.addAll(
            listOf(
                Feed(id = UUID.randomUUID().toString(), name = "GamersNexus", feedURL = "https://gamersnexus.net/rss.xml"),
                Feed(id = UUID.randomUUID().toString(), name = "9to5Google", feedURL = "https://9to5google.com/feed")
            )
        )

        val opmlFile = OPMLFile(
            path = accountPath,
            account = account
        )

        val documentSnapshot = """
        |<?xml version="1.0" encoding="UTF-8"?>
        |<!-- OPML generated by Basil Reader -->
        |<opml version="1.1">
        |  <head>
        |    <title>Test Display Name</title>
        |  </head>
        |  <body>
        |    <outline text="9to5Google" title="9to5Google" description="" type="rss" version="RSS" htmlUrl="" xmlUrl="https://9to5google.com/feed"/>
        |    <outline text="GamersNexus" title="GamersNexus" description="" type="rss" version="RSS" htmlUrl="" xmlUrl="https://gamersnexus.net/rss.xml"/>
        |    <outline text="Empty Folder" title="Empty Folder"/>
        |    <outline text="Programming" title="Programming">
        |      <outline text="De Programmatica Ipsum" title="De Programmatica Ipsum" description="" type="rss" version="RSS" htmlUrl="" xmlUrl="https://deprogrammaticaipsum.com/feed"/>
        |      <outline text="Ruby Weekly" title="Ruby Weekly" description="" type="rss" version="RSS" htmlUrl="" xmlUrl="https://cprss.s3.amazonaws.com/rubyweekly.com.xml"/>
        |    </outline>
        |    <outline text="Tech" title="Tech">
        |      <outline text="The Verge" title="The Verge" description="" type="rss" version="RSS" htmlUrl="" xmlUrl="https://www.theverge.com/rss/index.xml"/>
        |      <outline text="Ars Technica" title="Ars Technica" description="" type="rss" version="RSS" htmlUrl="" xmlUrl="https://feeds.arstechnica.com/arstechnica/index"/>
        |    </outline>
        |  </body>
        |</opml>
        """.trimMargin()

        assertEquals(opmlFile.opmlDocument(), documentSnapshot)
    }
}
