package com.jocmp.basil

import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import kotlin.test.assertEquals

class OPMLFileTest {
    @JvmField
    @Rule
    val folder = TemporaryFolder()

    @Test
    fun opmlDocument_serializes() {
        val accountPath = folder.newFile().toURI()

        val opmlFile = OPMLFile(
            path = accountPath,
            account = Account(id = "777", path = accountPath.resolve("test.opml"))
        )

        val documentSnapshot = """
        |<?xml version="1.0" encoding="UTF-8"?>
		|<!-- OPML generated by Basil Reader -->
        |<opml version="1.1">
		|  <head>
		|    <title>Test Display Name</title>
		|  </head>
        |  <body>
        |  </body>
        |</opml>
        """.trimMargin()

        assertEquals(opmlFile.opmlDocument(), documentSnapshot)
    }
}
