source "https://rubygems.org"

gem "rackup", "~> 2.1", require: false
gem "puma", "~> 6.4.3", require: false
gem "sinatra", require: false
gem "liquid"
gem "rexml", "~> 3.3.9"

group :development, :test do
  gem "sass-embedded"
  gem "rerun"
  gem "terminal-notifier"
  gem "rb-fsevent", "~> 0.11.2"
  gem "standard"
  gem "debug"
end
