package com.jocmp.basil

import com.jocmp.basil.common.escapingSpecialXMLCharacters
import com.jocmp.basil.opml.OPMLHandler
import com.jocmp.basil.opml.Outline
import java.io.File
import java.net.URI
import javax.xml.parsers.SAXParserFactory

class OPMLFile(
    val path: URI,
    val account: Account
) {
    internal fun save() {
        File(path).writeText(opmlDocument())
    }

    internal fun load(): List<Outline> {
        if (File(path).exists()) {
            return OPMLHandler.parse(path.toString())
        }

        return emptyList()
    }

    fun opmlDocument(): String {
        val escapedTitle = account.displayName.escapingSpecialXMLCharacters
        val openingText = """
        |<?xml version="1.0" encoding="UTF-8"?>
        |<!-- OPML generated by Basil Reader -->
        |<opml version="1.1">
        |  <head>
        |    <title>${escapedTitle}</title>
        |  </head>
        |  <body>
        |
		""".trimMargin()

        val closingText = """
        |  </body>
        |</opml>
        """.trimMargin()

        return openingText + account.asOPML() + closingText
    }
}
