package com.jocmp.basil

import java.net.URI

class OPMLFile(
    val path: URI,
    val account: Account
) {
    fun opmlDocument(): String {
        val escapedTitle = account.displayName
        val openingText = """
        |<?xml version="1.0" encoding="UTF-8"?>
        |<!-- OPML generated by Basil Reader -->
        |<opml version="1.1">
        |  <head>
        |    <title>${escapedTitle}</title>
        |  </head>
        |  <body>
        |
		""".trimMargin()

        val closingText = """
        |  </body>
        |</opml>
        """.trimMargin()

        return openingText + account.asOPML() + closingText
    }
}
