default_platform(:android)

platform :android do
  desc 'Validate Play Store key'
  lane :validate_key do
    validate_play_store_json_key
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :production do
    build_release
    upload_to_play_store
  end
end

def build_release
  gradle(task: 'clean bundleRelease')
end
