default_platform(:android)

platform :android do
  desc 'Validate Play Store key'
  lane :validate_key do
    validate_play_store_json_key
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :production do
    build_release_bundle
    upload_to_play_store
  end

  lane :github_release do
    build_apk_release
  end
end

def build_release_bundle
  gradle(task: 'clean bundleRelease')
end

def build_apk_release
  gradle(task: 'clean assembleRelease')
end
