#!/usr/bin/env ruby

require "fileutils"

def main
  filename = "template"

  file_content = File.read("./views/#{filename}.liquid")
  file_content = file_content.gsub("{{body}}", "")
  file_content = file_content.gsub("    {{debug_script}}\n", "")
  file_content = file_content.gsub('src="/', 'src="https://appassets.androidplatform.net/')
  file_content = file_content.gsub('href="/', 'href="https://appassets.androidplatform.net/')

  assert_clean(file_content)

  FileUtils.mkdir_p("dist")
  File.write("dist/#{File.basename("#{filename}.html")}", file_content)
end

def assert_clean(html)
  if html.include?("{{debug_script}}")
    raise "Debug tag detected"
  end
end

main
